### PR TITLE
Twittercard

### PR DESCRIPTION
**Pull request by tmock12**
@jwworth This adds the /priv/static back into .gitignore. 

I believe we should be able to serve the twittercard directly from web/static at `/images/til_twittercard.png`. 

I compiled and built assets locally in production and it seems to work ok. 

Can we try it? 😄 I'm happy to take the blame and quickly revert back if need be.

### CODE REVIEW

**Comment by tmock12** [comment]
Grr..not sure why the tests are failing on CI ¯\_(ツ)_/¯

**Comment by jwworth** [comment]
@tmock12 Nice. the issue is that the Twittercard has to be available at `https://til.hashrocket.com/assets/til_twittercard.png` for all previous links to our Twittercard to not break. If you can expose it there, or have another idea for exposing it at that URL, that would be great.

**Comment by tmock12** [comment]
ah ok, makes sense. Let me take a look at it.

**Comment by tmock12** [comment]
I nested it under `/assets`. That should still work. I compiled under production locally and it seems to be working as expected. So now the image should still be available at https://til.hashrocket.com/assets/til_twittercard.png and we shouldn't need to remove /priv/static from the gitignore.

**Comment by tmock12** [comment]
Looks like its working on that auto deployed app - https://tilex-staging-pr-102.herokuapp.com/assets/til_twittercard.png

**Comment by tmock12** [comment]
Ok, all tests passing. Travis now does the brunch build as well which is needed when we remove /priv/static. It took a few guesses at the Travis configuration 😄 . 

screen shot 2017-07-21 at 2 37 24 pm

**Comment by jwworth** [comment]
Thank you for taking the time to resolve this! 👍

**Pull request merged**
