### PR TITLE
WIP - Check the google user's email domain

### PR DESCRIPTION
**Pull request by jbranchaud**

### CODE REVIEW

**Comment by jbranchaud** [comment]
This is still a WIP. So far, it allows us to differentiate between hashrocket.com and other Google authentication requests.

**Comment by jbranchaud** [comment]
Asserting `redirected_to` and then pulling out `:phoenix_flash` feels a bit gross. Would love suggestions on how to better test this.

**Comment by jbranchaud** [comment]
There is definitely room for improvement here, but it may be worth merging this now to get the Developer concept into the system.

**Comment by jbranchaud** [comment]
@jwworth there is still some work to do around managing a user's session, but I'm okay with merging this now in order to get `Developer` into the system.

**Comment by jwworth** [comment]
Thank you! 👍

**Pull request merged**
